# Generated by Django 5.1.2 on 2025-04-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Product Image')),
                ('details', models.TextField(default='Product detail', verbose_name='Details')),
                ('price', models.IntegerField(verbose_name='Product Price')),
                ('category', models.IntegerField(choices=[(1, 'All'), (2, 'EV Bike'), (3, 'EV Car')], verbose_name='Category')),
                ('delevery_option', models.IntegerField(choices=[('free', 'Free Delevery'), ('paid', 'Paid Delevery')], verbose_name='Delevery Option')),
                ('discount', models.IntegerField(default=0, verbose_name='Discount')),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
    ]
