# Generated by Django 5.1.2 on 2025-04-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='battery_capacity',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Battery Capacity (e.g., 3.2 kWh)'),
        ),
        migrations.AddField(
            model_name='product',
            name='range_per_charge',
            field=models.IntegerField(blank=True, null=True, verbose_name='Range per Charge (km)'),
        ),
        migrations.AddField(
            model_name='product',
            name='voltage',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Voltage (e.g., 48V)'),
        ),
    ]
