# Generated by Django 5.1.2 on 2025-04-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cart_cartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(1, 'EV Bike'), (2, 'EV Car'), (3, 'Accessories')], verbose_name='Category'),
        ),
    ]
