# Generated by Django 5.1.2 on 2025-05-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_userprofile_user_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='order_picked',
            field=models.BooleanField(default=False),
        ),
    ]
